version: 1
frontend:
    phases:
      preBuild:
        commands:
            - 'npm i'
      build:
        commands:
            - 'npm run build'  # Build the project
    artifacts:
        baseDirectory: build
        files:
            - '**/*'
    cache:
        paths:
            - ''  # Specify paths to cache if needed; otherwise, you can leave it empty
